- name: Find the default gateway information on all servers
  hosts: all
  tasks:
    - name: Run `route print` to find the default gateway
      win_command:
        cmd: route print | find "0.0.0.0"
