- name: Install and start Apache HTTP server on all Linux servers
  hosts: all
  tasks:
    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present
      - name: Start Apache service
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes
