- name: Install Nginx on all Linux servers
  hosts: all
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present
      - name: Start Nginx service
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
